#!/bin/bash --login

#SBATCH --job-name=e_3d_s_d
#SBATCH --ntasks=1
#SBATCH --time=00:20:00
#SBATCH --account=e01-Lough-Su
#SBATCH --partition=standard
#SBATCH --qos=short

module list

export TTWORKPLACE=/work/e01/e01/ttuw_archer2
export PYFR_SOURCE=$TTWORKPLACE/source

#For srun
export SRUN_CPUS_PER_TASK=$SLURM_CPUS_PER_TASK
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_PLACES=cores

#pyFR1.15
#export PYTHONUSERBASE=$TTWORKPLACE/.local
#export PATH=$PYTHONUSERBASE/bin:$PATH
#export PYTHONPATH=$PYTHONUSERBASE/lib/python3.9/site-packages:$PYTHONPATH
#export PYFR_XSMM_LIBRARY_PATH=$PYFR_SOURCE/pyFRv1.15/libxsmm/lib/libxsmm.so
#export PYFR_METIS_LIBRARY_PATH=$PYFR_SOURCE/pyFRv1.15/metis-5.1.0/lib/libmetis.so
#source $PYFR_SOURCE/pyFRv1.15/pyfr-venv/bin/activate

#pyFR2.0
export PYTHONPATH=$PYFR_SOURCE/pyFRv2.0/mambaforge:$PYTHONPATH
export PATH=$PYFR_SOURCE/pyFRv2.0/mambaforge/bin:$PATH
export PYFR_XSMM_LIBRARY_PATH=$PYFR_SOURCE/pyFRv2.0/libxsmm/lib/libxsmm.so
export PYFR_METIS_LIBRARY_PATH=$PYFR_SOURCE/pyFRv2.0/mambaforge/envs/pyFRv2.0/lib/libmetis.so
source $PYFR_SOURCE/pyFRv2.0/mambaforge/etc/profile.d/conda.sh 
source $PYFR_SOURCE/pyFRv2.0/mambaforge/etc/profile.d/mamba.sh 
mamba activate pyFRv2.0

pyfr --version

pyfr import 3d_sbli_h_d.msh 3d_sbli_h_d.pyfrm 

pyfr partition 320 3d_sbli_h_d.pyfrm  .

echo 'Import Complete'
