# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:

# export SYSTEMD_PAGER=

#export
export home=/home/t/ttuw_sulis

# User specific aliases and functions
alias home="cd /home/t/ttuw_sulis/"
alias sff="cd /home/t/ttuw_sulis/SFF/"
alias pyfr-venv="source $home/PyFR/libxsmm/pyfr-venv/bin/activate"

#PyFR
export PYFR_XSMM_LIBRARY_PATH=$home/PyFR/libxsmm/lib/libxsmm.so
alias loadpyfr="module load GCC/10.3.0 GCCcore/10.3.0 Python/3.9.5 METIS/5.1.0 Op
enMPI/4.1.1"
alias unloadpyfr="module purge"

#OpenFOAM8
alias of8="module load GCC/10.2.0  OpenMPI/4.0.5 OpenFOAM/8"
alias unloadof8="module purge"
