#!/bin/bash
#SBATCH --job-name=pyfrg
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=16
#SBATCH --gres=gpu:4
#SBATCH --time=0:30:00
#SBATCH --account=Watson2025a
#SBATCH --partition=gpu

module purge
module load Python/3.11.3-GCCcore-12.3.0 OpenMPI/4.1.5-GCC-12.3.0 CMake/3.26.3-GCCcore-12.3.0 CUDA/12.3.0;
module list

export TTWORKPLACE=/data/home/tt/ttuw
export PYFR_INSTALL_DIRECTORY=$TTWORKPLACE/source/pyFRv2.1
export PATH=$PYFR_INSTALL_DIRECTORY/pyfr2.1_venv/bin:$PATH
export PYFR_XSMM_LIBRARY_PATH=$PYFR_INSTALL_DIRECTORY/libxsmm/lib/libxsmm.so
export PYFR_SCOTCH_LIBRARY_PATH=$PYFR_INSTALL_DIRECTORY/scotch-v7.0.9/build/lib/libscotch.so

#Activating PyFR
source $PYFR_INSTALL_DIRECTORY/pyfr2.1_venv/bin/activate;

pyfr --version

echo Importing mesh
pyfr import taylor-green.msh taylor-green.pyfrm

echo Partitioning
pyfr partition $SLURM_NTASKS  taylor-green.pyfrm .
echo Partition complete

mpirun --map-by numa:PE=$SLURM_CPUS_PER_TASK -np $SLURM_NTASKS pyfr -p run -b cuda taylor-green.pyfrm taylor-green.ini
